language: objective-c
osx_image: xcode6.4
before_install:
  - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profiles/WildcardDist.mobileprovision.enc -d -a -out scripts/profiles/WildcardDist.mobileprovision
  - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/ios_development.cer.enc -d -a -out scripts/certs/ios_development.cer
  - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/ios_distribution.cer.enc -d -a -out scripts/certs/ios_distribution.cer
  - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dev.p12.enc -d -a -out scripts/certs/dev.p12
  - ./scripts/add-key.sh
  - curl -L -O https://github.com/Carthage/Carthage/releases/download/0.9.2/Carthage.pkg
  - sudo installer -pkg Carthage.pkg -target /
  - carthage bootstrap --verbose --platform iOS
before_script:
  - ./scripts/update-bundle.sh
script:
  - xctool test -project todo-split-objc.xcodeproj -scheme todo-split-objc -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6'
after_script:
  - ./scripts/remove-key.sh
env:
  global:
    - APP_NAME="todo-split"
    - 'DEVELOPER_NAME="iPhone Distribution: akiraspeirs@gmail.com (GG7WCKRC5T)"'
    - DEV_PROFILE_NAME="WildcardDev"
    - DIST_PROFILE_NAME="WildcardDist"
    - INFO_PLIST="todo-split-objc/Info.plist"
    - BUNDLE_DISPLAY_NAME="todo-split"
    - secure: PAEm8J9R+qnDv9XMKlde2FnCz+f/TbSu2agnXeMDdynOyLkRLIf0GsZ6024iF/agJ/h+/FPKYPm48p/pDQlT9WLezOcEN7OxPDb2+ADXXhISFtETIUfDMUxNLdRx0ORoeZUEScE9HUFs9LmBjvt9h/yVfdSE6SgN8BDH99Ap7eLREgstCmLmiOfEwt44fA0luXL8C5gFOSEDOMy4bjceEFP/HY/vtPXxvuKwjwQTxuoJSjhibZ6f/x1DIBzd4xNzJJKVZXpxieDypNCWoHJkt9ZGArjBzkADtbcrr7MC10uyYntMrGzkYJ1In3qI/kvHGU5s3FAAvTe/JiMlzslJOKGCxLJtvToCdCPOxITqny0wJEzaFJKo9FXzjtiCuDA+RzSPOWWFl6Oh8jPGCLALk5XBGOf5LIdegU8Vu9LPxevlOGAvlHsVg5yKPES88+diWwlp2LJeZ9feht+6VbprDkpNhuXHnT9uHMEloswoYxkOxbHkAYX2Y5ygQde6xMUHduKkmkvQBOH07wqxBfFu1rWSHwaWtUTboaFjpM1fonf9MPBG5ZI/qlXxWXNfqfMIK2upUBPcGdybAb1iuDi0fIcH58HrafsFm9tzAt2NhpagwmVd53ntx4/KDT1dQUD155n8A6JU/NvqJ0GJi6eA+WOmpQ1HJV7dYg+7NFXEu6E=
    - secure: vP1xDNihhuX6k/qag0lpNmf1/zMTvv/blsUDvVmSQ0UaJVldfUtrvF0Y7PTgX1lkJdoYhr8X57B53kqG0SX+hPUhbUDQGUNo8GqabZ6h165LwfXX56gDGnuix2CoUl2Vjg4cBY3zat6ziezHnHy/8gnENEPY8yRXQMjxXpkdqas0m0XWEp3/IYJkZ62ih9dEeCnK8x3YRmS/XMk8sVtihxzQToThQYdxdFja2jtJFnWA+yWXAjGUcyLhimebrW8lvMdobzM8OkDc8B8exL16hom6R7aSFZ2h/x5Z3znQgIRubLn1/dlSwhzH0rcL9z/Zf+PQ81iMb41W24VUdenlDagMxhVO8iCtY8B26G1BWNGNcLdQdoct9Kd1+aj158+V8vPytgkKXsox/7FWZX8FbMpy/o51/A24fYQWiLHg2KB+JrrrcEU7erqb3vf2gI4xVURx0H7ciEtR7c7NU+slJS6sah9nzbMnCaDrXxKL8Pw6kGdcaFzReOG33FWhHA80b/2A6GpWMzuboLFZs95gmScRM3PYAPVyq2rrKD9XEi8GSlKQIfQ2zwr3g6s4Wna2aBSPT7CFhXTl2TvGvSJwWtgnTdff0b6/0OYyqDYi8ZjkN5UAsauN9IO7Gd/BdID3gaBS1ppf5kDlJiGlKLTrGt6G4o451t0gfo9pZitk4Hk=
    - secure: PVdbCJxV3xblyW52h3hJ4QywSAkMoeCbCxtfFFJzIuhkkZl1unO8kryxFkn2sEWoxnrc6aeKcrL0FbcCdkU07yXdq5yChWXuFvYcmYutKZ7liwhzAs9jyLK7wh+0vPUvEhHDWqvR0L3Ujv08Jz5ZC7tv9nQ1liZnrb79jd3JgnzXr32WJXPK+rPYEYGuoErPR8N7YEbVWOV6F2+gNXsoY0wO7fzScPP81QW3nov1N7/aOeLU6ZZ6AUaAgYhWxVQRKoflaRj7rwvDOMtQAUDwmGwHo7h4Ke86uxFbra5Rl2gWeMXcx9A2T9J80vRvpHD8q/M50JjK/TcQZ1gnM8VZzAt+bY94r5HNIdO9HsHKEdBGzZIw5l10fe8armSvfkGJyUOUrr/cCzo6vRheC9MsnvMMmRTfdyIX6Y0q71CVuLGh4RVWvBjjD+Okn8sPpcl2LC3gmen9t2pOznMScqpzP0HF3ps5WGDV+JzVHuQ7bScND0mi8cxs36V2V59G8tiaJtZF3ijt6CWZOD5j1KE9xtqx1klWxNd6c2ZTv+e37YL/FGOO/1sn5qvPi8dvcf/4Vx13RipMo70fRQcrFJnG3wR63WpP84jJBf5GOkM17cZqOgihABTFi0lJlN2TYbQ5QzpccdwbnL44t+HMC5kXN6LNULdXn4uJ2PibpqR9uW8=
